[package]
name = "sftp-git"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"
description = "SFTPアップロードとGit管理を統合し、バージョンレスAPIとバージョン管理のハイブリッド運用でWEBサイト開発者の手間とミスを減らすツール(構想段階)"
repository = "https://github.com/aon-co-jp/sftp-git"

[lib]
name = "sftp_git"
path = "src/lib.rs"

[dependencies]
open-runo-versionless-api = { path = "../RPoem/crates/open-runo-versionless-api" }
open-runo-rustjson = { path = "../RPoem/crates/open-runo-rustjson" }
lsp-server = "0.10.0"
lsp-types = "0.97.0"
reqwest = { version = "0.13.4", features = ["json"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sha2 = "0.11.0"
ssh2 = "0.9.6"
tokio = { version = "1.53.1", features = ["full"] }
tokio-postgres = "0.7.18"
